Search.appendIndex(
    [
                {
            "fqsen": "\\distanceGeoPoints\u0028\u0029",
            "name": "distanceGeoPoints",
            "summary": "",
            "url": "namespaces/default.html#function_distanceGeoPoints"
        },                {
            "fqsen": "\\getAdviesArray\u0028\u0029",
            "name": "getAdviesArray",
            "summary": "",
            "url": "namespaces/default.html#function_getAdviesArray"
        },                {
            "fqsen": "\\getFuelPrices\u0028\u0029",
            "name": "getFuelPrices",
            "summary": "",
            "url": "namespaces/default.html#function_getFuelPrices"
        },                {
            "fqsen": "\\TweedeKamer",
            "name": "TweedeKamer",
            "summary": "",
            "url": "classes/TweedeKamer.html"
        },                {
            "fqsen": "\\TweedeKamer\u003A\u003AgetRandomActiviteitOpDag\u0028\u0029",
            "name": "getRandomActiviteitOpDag",
            "summary": "",
            "url": "classes/TweedeKamer.html#method_getRandomActiviteitOpDag"
        },                {
            "fqsen": "\\TweedeKamer\u003A\u003AgetGeschenk\u0028\u0029",
            "name": "getGeschenk",
            "summary": "",
            "url": "classes/TweedeKamer.html#method_getGeschenk"
        },                {
            "fqsen": "\\TweedeKamer\u003A\u003AgetActiviteitTekst\u0028\u0029",
            "name": "getActiviteitTekst",
            "summary": "",
            "url": "classes/TweedeKamer.html#method_getActiviteitTekst"
        },                {
            "fqsen": "\\TweedeKamer\u003A\u003AgetGeschenkTekst\u0028\u0029",
            "name": "getGeschenkTekst",
            "summary": "",
            "url": "classes/TweedeKamer.html#method_getGeschenkTekst"
        },                {
            "fqsen": "\\TweedeKamer\u003A\u003A\u0024arrContextOptions",
            "name": "arrContextOptions",
            "summary": "",
            "url": "classes/TweedeKamer.html#property_arrContextOptions"
        },                {
            "fqsen": "\\verjaardag",
            "name": "verjaardag",
            "summary": "",
            "url": "classes/verjaardag.html"
        },                {
            "fqsen": "\\verjaardag\u003A\u003AsetGeboortedatums\u0028\u0029",
            "name": "setGeboortedatums",
            "summary": "",
            "url": "classes/verjaardag.html#method_setGeboortedatums"
        },                {
            "fqsen": "\\verjaardag\u003A\u003AgetVerjaardagen\u0028\u0029",
            "name": "getVerjaardagen",
            "summary": "",
            "url": "classes/verjaardag.html#method_getVerjaardagen"
        },                {
            "fqsen": "\\verjaardag\u003A\u003AgetVerjaardagenData\u0028\u0029",
            "name": "getVerjaardagenData",
            "summary": "",
            "url": "classes/verjaardag.html#method_getVerjaardagenData"
        },                {
            "fqsen": "\\verjaardag\u003A\u003AgetVerjaardagTekst\u0028\u0029",
            "name": "getVerjaardagTekst",
            "summary": "",
            "url": "classes/verjaardag.html#method_getVerjaardagTekst"
        },                {
            "fqsen": "\\verjaardag\u003A\u003A\u0024geboortedatums",
            "name": "geboortedatums",
            "summary": "",
            "url": "classes/verjaardag.html#property_geboortedatums"
        },                {
            "fqsen": "\\weekend",
            "name": "weekend",
            "summary": "",
            "url": "classes/weekend.html"
        },                {
            "fqsen": "\\weekend\u003A\u003AsetWeekenden\u0028\u0029",
            "name": "setWeekenden",
            "summary": "",
            "url": "classes/weekend.html#method_setWeekenden"
        },                {
            "fqsen": "\\weekend\u003A\u003AgetWeekenden\u0028\u0029",
            "name": "getWeekenden",
            "summary": "",
            "url": "classes/weekend.html#method_getWeekenden"
        },                {
            "fqsen": "\\weekend\u003A\u003AgetWeekendByJaar\u0028\u0029",
            "name": "getWeekendByJaar",
            "summary": "",
            "url": "classes/weekend.html#method_getWeekendByJaar"
        },                {
            "fqsen": "\\weekend\u003A\u003AgetWeekendText\u0028\u0029",
            "name": "getWeekendText",
            "summary": "",
            "url": "classes/weekend.html#method_getWeekendText"
        },                {
            "fqsen": "\\weekend\u003A\u003A\u0024weekenden",
            "name": "weekenden",
            "summary": "",
            "url": "classes/weekend.html#property_weekenden"
        },                {
            "fqsen": "\\getKabinet\u0028\u0029",
            "name": "getKabinet",
            "summary": "",
            "url": "namespaces/default.html#function_getKabinet"
        },                {
            "fqsen": "\\getBitcoinPrice\u0028\u0029",
            "name": "getBitcoinPrice",
            "summary": "",
            "url": "namespaces/default.html#function_getBitcoinPrice"
        },                {
            "fqsen": "\\getEthereumPrice\u0028\u0029",
            "name": "getEthereumPrice",
            "summary": "",
            "url": "namespaces/default.html#function_getEthereumPrice"
        },                {
            "fqsen": "\\getDagVanDe\u0028\u0029",
            "name": "getDagVanDe",
            "summary": "",
            "url": "namespaces/default.html#function_getDagVanDe"
        },                {
            "fqsen": "\\getNews\u0028\u0029",
            "name": "getNews",
            "summary": "",
            "url": "namespaces/default.html#function_getNews"
        },                {
            "fqsen": "\\getHackerNews\u0028\u0029",
            "name": "getHackerNews",
            "summary": "",
            "url": "namespaces/default.html#function_getHackerNews"
        },                {
            "fqsen": "\\getMop\u0028\u0029",
            "name": "getMop",
            "summary": "",
            "url": "namespaces/default.html#function_getMop"
        },                {
            "fqsen": "\\getWeather\u0028\u0029",
            "name": "getWeather",
            "summary": "",
            "url": "namespaces/default.html#function_getWeather"
        },                {
            "fqsen": "\\getWaarschuwing\u0028\u0029",
            "name": "getWaarschuwing",
            "summary": "",
            "url": "namespaces/default.html#function_getWaarschuwing"
        },                {
            "fqsen": "\\getDaysSince\u0028\u0029",
            "name": "getDaysSince",
            "summary": "",
            "url": "namespaces/default.html#function_getDaysSince"
        },                {
            "fqsen": "\\getVandaag\u0028\u0029",
            "name": "getVandaag",
            "summary": "",
            "url": "namespaces/default.html#function_getVandaag"
        },                {
            "fqsen": "\\getWeekNumberToday\u0028\u0029",
            "name": "getWeekNumberToday",
            "summary": "",
            "url": "namespaces/default.html#function_getWeekNumberToday"
        },                {
            "fqsen": "\\getThuisarts\u0028\u0029",
            "name": "getThuisarts",
            "summary": "",
            "url": "namespaces/default.html#function_getThuisarts"
        },                {
            "fqsen": "\\isToday\u0028\u0029",
            "name": "isToday",
            "summary": "",
            "url": "namespaces/default.html#function_isToday"
        },                {
            "fqsen": "\\get_prijzen_parade_url\u0028\u0029",
            "name": "get_prijzen_parade_url",
            "summary": "",
            "url": "namespaces/default.html#function_get_prijzen_parade_url"
        },                {
            "fqsen": "\\getTourRanking\u0028\u0029",
            "name": "getTourRanking",
            "summary": "",
            "url": "namespaces/default.html#function_getTourRanking"
        },                {
            "fqsen": "\\getTourInfo\u0028\u0029",
            "name": "getTourInfo",
            "summary": "",
            "url": "namespaces/default.html#function_getTourInfo"
        },                {
            "fqsen": "\\getParsedCalendar\u0028\u0029",
            "name": "getParsedCalendar",
            "summary": "",
            "url": "namespaces/default.html#function_getParsedCalendar"
        },                {
            "fqsen": "\\getFormattedDate\u0028\u0029",
            "name": "getFormattedDate",
            "summary": "",
            "url": "namespaces/default.html#function_getFormattedDate"
        },                {
            "fqsen": "\\getFormattedIntervalDays\u0028\u0029",
            "name": "getFormattedIntervalDays",
            "summary": "",
            "url": "namespaces/default.html#function_getFormattedIntervalDays"
        },                {
            "fqsen": "\\getKoersenTekst\u0028\u0029",
            "name": "getKoersenTekst",
            "summary": "",
            "url": "namespaces/default.html#function_getKoersenTekst"
        },                {
            "fqsen": "\\getCyclingNews\u0028\u0029",
            "name": "getCyclingNews",
            "summary": "",
            "url": "namespaces/default.html#function_getCyclingNews"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
