name: Fix Code Style
on: [push,workflow_call]
jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Composer Install
        run: composer install
      - name: Run Laravel Pint
        run: ./vendor/bin/pint
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Laravel Pint changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}