name: PHPStan
on: workflow_dispatch
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          path: php/
          configuration: ./phpstan.neon
