on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

name: Upload Snorbot test
jobs:
  test:
    uses: ./.github/workflows/test.yml
  web-deploy:
    name: 🎉 Deploy
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.ftpservertest }}
          username: ${{ secrets.ftpusernametest }}
          password: ${{ secrets.ftppasswordtest }}
          exclude: |
            **/.git*
            **/.git*/**
            **/vendor/**
            **/tests/**
