on:
  push:
    branches:
      - master
name: Upload Snorbot
jobs:
  test:
    uses: ./.github/workflows/test.yml
  web-deploy:
    name: 🎉 Deploy
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftpserver }}
          username: ${{ secrets.ftpusername }}
          password: ${{ secrets.ftppassword }}
          exclude: |
            **/.git*
            **/.git*/**
            **/vendor/**
            **/tests/**
